-- Criação das sequencias (sequences)

CREATE SEQUENCE seq_blt NOCACHE;
CREATE SEQUENCE seq_cat NOCACHE;
CREATE SEQUENCE seq_cot NOCACHE;
CREATE SEQUENCE seq_grp NOCACHE;
CREATE SEQUENCE seq_prd NOCACHE;
CREATE SEQUENCE seq_pap NOCACHE;
CREATE SEQUENCE seq_tap NOCACHE;
CREATE SEQUENCE seq_umd NOCACHE;

-- Criação dos gatilhos (triggers)

CREATE TRIGGER tg_seq_blt
BEFORE INSERT ON BOLETIM
FOR EACH ROW
BEGIN
    :NEW.blt_id := seq_blt.NEXTVAL;
END;
/

CREATE TRIGGER tg_seq_cat
BEFORE INSERT ON CATEGORIA
FOR EACH ROW
BEGIN
    :NEW.cat_id := seq_cat.NEXTVAL;
END;
/

CREATE TRIGGER tg_seq_cot
BEFORE INSERT ON COTACAO
FOR EACH ROW
BEGIN
    :NEW.cot_id := seq_cot.NEXTVAL;
END;
/

CREATE TRIGGER tg_seq_grp
BEFORE INSERT ON GRUPO_ALIMENTAR
FOR EACH ROW
BEGIN
    :NEW.grp_id := seq_grp.NEXTVAL;
END;
/

CREATE TRIGGER tg_seq_prd
BEFORE INSERT ON PRODUTO
FOR EACH ROW
BEGIN
    :NEW.prd_id := seq_prd.NEXTVAL;
END;
/

CREATE TRIGGER tg_seq_pap
BEFORE INSERT ON PRODUTO_APRESENTACAO
FOR EACH ROW
BEGIN
    :NEW.pap_id := seq_pap.NEXTVAL;
END;
/

CREATE TRIGGER tg_seq_tap
BEFORE INSERT ON TIPO_APRESENTACAO
FOR EACH ROW
BEGIN
    :NEW.tap_id := seq_tap.NEXTVAL;
END;
/

CREATE TRIGGER tg_seq_umd
BEFORE INSERT ON UNIDADE_MEDIDA
FOR EACH ROW
BEGIN
    :NEW.umd_id := seq_umd.NEXTVAL;
END;
/